### Import Numpy

In [6]:
import numpy as np

#### Erstellen eines Numpy-Arrays

In [7]:
array_1 = np.array([1, 2, 3, ])
array_1

array([1, 2, 3])

#### Eine Liste in ein Numpy-Array konvertieren

In [8]:
numbers = [9, 8, 7, 6]
array_2 = np.array(numbers)
array_2

array([9, 8, 7, 6])

#### Erstellung eines Numpy-Array mit 3 Zeilen und 4 Spalten, das nur 0's enthält

In [9]:
array_of_zeroes = np.zeros((3,4))
array_of_zeroes

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### Erstellung eines Numpy-Array mit 3 Zeilen und 4 Spalten, das nur 1's enthält

In [10]:
array_of_ones = np.ones((3,4))
array_of_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### Erstellung eines Numpy-Array mit 3 Zeilen und 4 Spalten, das nur den Typ Integer enthält

In [11]:
array_of_ones_int = np.ones((3,4), dtype=np.int16)
array_of_ones_int

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

#### Erstellung eines Numpy Araray, ohne die Schätzer zu initialisieren 

In [12]:
array_empty = np.empty((2,3))
array_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

#### Erstellung eines Numpy-Array in Form einer Matrix mit Diagonalen von "1" und dem Rest "0".

In [13]:
array_eye = np.eye(3)
array_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Diese Funktion gibt gerade Zahlen zwischen 2 und 20 zurück

In [14]:
array_of_evens = np.arange(2, 20, 2)   # np.arange(start, end, step)
array_of_evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

#### Tabellen mit 2 Zeilen und 3 Spalten erstellen

In [15]:
array_2d = np.array([(2,4,6), (3,5,7)])
array_2d

array([[2, 4, 6],
       [3, 5, 7]])

In [16]:
array_2d.shape   # Nombre de lignes et colonnes

(2, 3)

#### Erstellung eines Array mit 6 Elementen, die von "0" bis "5" gehen. 

In [17]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

#### Erstellung einer Tabelle mit 3 Zeilen und 2 Spalten, die die Zahlen von "0" bis "5" enthält.

In [18]:
array_nd = np.arange(6).reshape(3,2)
array_nd

array([[0, 1],
       [2, 3],
       [4, 5]])

#### Kopieren der Struktur eines Arrays

In [23]:
array_ones = np.ones_like(array_nd)
array_ones

array([[1, 1],
       [1, 1],
       [1, 1]])

###  Array-Operationen

In [24]:
a = np.array([10,10,10])
b = np.array([5,5,5])

#### Array Addieren

In [25]:
a + b

array([15, 15, 15])

#### Array Subtrahieren 

In [26]:
a - b

array([5, 5, 5])

#### Array Multiplizieren

In [27]:
a * b

array([50, 50, 50])

#### Array Dividieren

In [28]:
a / b

array([2., 2., 2.])

#### Array Modulo

In [29]:
a % 3

array([1, 1, 1], dtype=int32)

#### Berechnung der Summe mit  ".sum()".

In [30]:
ages = np.array([12,15,18,20])

In [31]:
ages.sum()

65

#### Bestimmung des Minimum und Maximum eines Arrays mit ".min()", ".max()".

In [32]:
ages.min()

12

In [33]:
ages.max()

20

#### Summe einer Matrix auf ihren Spalten

In [34]:
numbers = np.arange(12).reshape(3,4)
numbers

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
numbers.sum(axis=0)

array([12, 15, 18, 21])

#### Summation einer Matrix auf ihren Zeilen

In [36]:
numbers.sum(axis=1)

array([ 6, 22, 38])

#### Minimum und Maximum einer Matrix auf ihren Spalten

In [37]:
numbers.min(axis=0)

array([0, 1, 2, 3])

In [38]:
numbers.max(axis=0)

array([ 8,  9, 10, 11])

#### Minimum und Maximum einer Matrix auf ihren Zeilen 

In [39]:
numbers.min(axis=1)

array([0, 4, 8])

In [40]:
numbers.max(axis=1)

array([ 3,  7, 11])

### Bedingte Operatoren auf Arrays

a < 35

In [41]:
a > 35

array([False, False, False])

### Operation auf 2 Arrays

In [42]:
A = np.array( [[1,1], [0,1]] )
B = np.array( [[2,1], [3,4]] )

print("A:\n", A)
print("B:\n", B)

A:
 [[1 1]
 [0 1]]
B:
 [[2 1]
 [3 4]]


#### Matrix-Multiplikation ".dot()"

In [43]:
A.dot(B)

array([[5, 5],
       [3, 4]])

In [44]:
np.dot(A,B)

array([[5, 5],
       [3, 4]])

#### Matrix-Addition

In [45]:
b += a     # b = b + a
b

array([15, 15, 15])

#### Matrix-Multiplication

In [46]:
a *= 3     # a = a *3
a

array([30, 30, 30])

### trigonometrische Funktionen mit Nunpy. Es geht bis zu 90 Grad


In [47]:
angles = np.array([0,30,45,60,90]) 

#### Umrechnung von Grad in Radiant
Winkel müssen durch Multiplikation mit pi/180 in Bogenmaß umgewandelt werden. Nur dann können wir trigonometrische Funktionen an unsere Anordnung anhängen.

In [48]:
angles_radians = angles * np.pi/180
angles_radians

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

#### Umrechnung in Radian mit einer Numpy-Funktion

In [49]:
angles_radians = np.radians(angles)
angles_radians

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

#### Sinus berechnen

In [67]:
print('Sine of angles in the array:')
print(np.sin(angles_radians))  

Sine of angles in the array:
[0.         0.5        0.70710678 0.8660254  1.        ]


#### Cosinus berechnen

In [68]:
print('Cosine of angles in the array:')
print(np.cos(angles_radians))

Cosine of angles in the array:
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


#### Tangente Berechnen

In [69]:
print('Tangent of angles in the array:')
print(np.tan(angles_radians))

Tangent of angles in the array:
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


#### Berechnung von Arcsin arccos und arctan

In [70]:
sin = np.sin(angles * np.pi/180) 
print ('Compute sine inverse of angles. Returned values are in radians.')

inv = np.arcsin(sin) 
print (inv) 

Compute sine inverse of angles. Returned values are in radians.
[0.         0.52359878 0.78539816 1.04719755 1.57079633]


#### np.degrees() wandelt Radiant in Grad um

In [71]:
print ('Check result by converting to degrees:' )
print (np.degrees(inv)) 

Check result by converting to degrees:
[ 0. 30. 45. 60. 90.]


### Statistische Funktionen

In [72]:
test_scores = np.array([32.32, 56.98, 21.52, 44.32, 
                        55.63, 13.75, 43.47, 43.34])

#### Berechnung des Mittelwertes.

In [73]:
print('Mean test scores of the students: ')
print(np.mean(test_scores))

Mean test scores of the students: 
38.91625


#### Berechnung des Medians

In [74]:
print('Median test scores of the students: ')
print(np.median(test_scores))

Median test scores of the students: 
43.405


### Beispiel auf statistische Daten "salary.csv" 
Wir werden nun grundlegende statistische Methoden an realen Datensätzen durchführen. Wir werden Gehaltsdaten von 1147 europäischen Entwicklern verwenden.

In [75]:
salaries = np.genfromtxt('data/salary.csv', 
                         delimiter=',')

salaries

array([60000., 58000., 56967., ..., 54647., 25000., 70000.])

salaries.shape

In [76]:
salary_min = np.min(salaries)
print("Salary Minimum: ", salary_min)
salary_max = np.max(salaries)
print("Salary Maximum: ", salary_max)

Salary Minimum:  11400.0
Salary Maximum:  850000.0


In [77]:
mean     = np.mean(salaries)
median   = np.median(salaries)
sd       = np.std(salaries)
variance = np.var(salaries)

In [78]:
print('Mean = %i' %mean)
print('Median = %i' %median)
print('Standard Deviation = %i' %sd)
print('Variance = %i' %variance)

Mean = 55894
Median = 48000
Standard Deviation = 55170
Variance = 3043770333


## Indizierung und Slicing

# 1D Arrays
Eindimensionale Arrays können wie Listen und andere Python-Sequenzen indiziert, in Scheiben geschnitten und darüber iteriert werden. Für das Slicing wird die Notation <b>(start:stop:step)</b> verwendet

#### Erhöhen Sie die Werte eines Arrays zum Quadrat

In [79]:
a = np.arange(11)**2
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

#### Dritter Eintrag auf der Liste auslesen

In [80]:
a[2]

4

#### Vorletzter Eintrag auf der Liste auslesen

In [81]:
a[-2]

81

#### Vom 3. Punkt in der Liste zum 8. Punkt in der Liste abrufen

In [82]:
a[2:7]

array([ 4,  9, 16, 25, 36], dtype=int32)

#### 3. Punkt in der Liste bis zum vorletzten auslesen

In [83]:
a[2:-2]

array([ 4,  9, 16, 25, 36, 49, 64], dtype=int32)

#### vom 3. Punkt der Liste bis zum Ende auslesen

In [84]:
a[2:]

array([  4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

#### von 1. Punkt der Liste bis zum 8. auslesen

In [85]:
a[:7]

array([ 0,  1,  4,  9, 16, 25, 36], dtype=int32)

#### Start : end : step

In [86]:
a[:11:2]

array([  0,   4,  16,  36,  64, 100], dtype=int32)

In [87]:
a[::-1]

array([100,  81,  64,  49,  36,  25,  16,   9,   4,   1,   0], dtype=int32)

## 2D Arrays
Hier wird die Daten von Studenten analysiert. Der Datensatz enthält die Testergebnisse in zwei Kursen der Studenten gegen ihre Namen

In [88]:
students = np.array([['Alice','Beth','Cathy','Dorothy'],
                     [65,78,90,81],
                     [71,82,79,92]])

In [89]:
students

array([['Alice', 'Beth', 'Cathy', 'Dorothy'],
       ['65', '78', '90', '81'],
       ['71', '82', '79', '92']], dtype='<U7')

#### 1., 2., 3. Element des Array auslesen

In [90]:
students[0]

array(['Alice', 'Beth', 'Cathy', 'Dorothy'], dtype='<U7')

In [91]:
students[1]

array(['65', '78', '90', '81'], dtype='<U7')

In [92]:
students[2]

array(['71', '82', '79', '92'], dtype='<U7')

#### Abrufen des 2. Elements aus der Liste 1.

In [93]:
students[0,1]

'Beth'

### 2D Array slicing
Dabei werden die Zeilen 0 und 1, Spalten 2 und 3 berücksichtigt.

In [94]:
students[0:2,2:4]

array([['Cathy', 'Dorothy'],
       ['90', '81']], dtype='<U7')

##### Alle Zeilen und Spalte 1

In [95]:
students[:,1:2]

array([['Beth'],
       ['78'],
       ['82']], dtype='<U7')

##### Alle Zeilen und Spalte 1 und 2

In [96]:
students[:,1:3]

array([['Beth', 'Cathy'],
       ['78', '90'],
       ['82', '79']], dtype='<U7')

##### Alle Spalte und Zeile 0 und 1

In [97]:
students[0:2,:]

array([['Alice', 'Beth', 'Cathy', 'Dorothy'],
       ['65', '78', '90', '81']], dtype='<U7')

#### Alle Spalte und Zeile

In [98]:
students[:]

array([['Alice', 'Beth', 'Cathy', 'Dorothy'],
       ['65', '78', '90', '81'],
       ['71', '82', '79', '92']], dtype='<U7')

#### Letzte Zeile

In [99]:
students[-1,:]

array(['71', '82', '79', '92'], dtype='<U7')

#### 3. von letzter bis zweiter von letzter Reihe, letzte zwei Spalten

In [100]:
students[-3:-1,-2:]

array([['Cathy', 'Dorothy'],
       ['90', '81']], dtype='<U7')